[package]
name = "vfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5"
thiserror = "1.0"
log = "0.4"
walkdir = "2"
zip = "0.6.2"
ftp = "3.0.1"
